import React, { useState } from 'react';
import {
  X,
  Ruler,
  Printer,
  Copy,
  Check,
  Volume2,
  VolumeX,
  Scissors,
  Camera,
  Shirt,
  User,
  Sparkles,
  Sliders,
  CheckCircle2,
  FileText,
  Clock,
  Layers,
  ArrowRight
} from 'lucide-react';
import { Client, GarmentMeasurements, StudioSettings } from '../../types';

interface FullMeasurementsModalProps {
  isOpen: boolean;
  onClose: () => void;
  client: Client;
  studioSettings?: StudioSettings;
  onUpdateClientPhoto?: (clientId: string, photoUrl: string) => void;
  onOpenMeasurements?: (client: Client) => void;
}

export const FullMeasurementsModal: React.FC<FullMeasurementsModalProps> = ({
  isOpen,
  onClose,
  client,
  studioSettings,
  onUpdateClientPhoto,
  onOpenMeasurements
}) => {
  const [unit, setUnit] = useState<'inches' | 'cm'>('inches');
  const [seamAllowance, setSeamAllowance] = useState<number>(0); // extra inches (default to 0 for exact match)
  const [copied, setCopied] = useState(false);
  const [isSpeaking, setIsSpeaking] = useState(false);
  const [clientPhoto, setClientPhoto] = useState<string>(
    client.avatarUrl || ''
  );

  // Cutting checklist state
  const [checklist, setChecklist] = useState<Record<string, boolean>>({
    fabricInspected: true,
    grainlineAligned: false,
    seamAdded: true,
    liningMatched: false,
    interfacingPrecut: false
  });

  if (!isOpen) return null;

  const m: GarmentMeasurements = client.measurements || {};

  // Unit conversion helper
  const formatVal = (valStr?: string) => {
    if (!valStr || valStr === '0.0"' || valStr === '0' || valStr === '0.0' || valStr === '—') return '—';
    const cleanStr = valStr.replace(/[^0-9.]/g, '');
    const num = parseFloat(cleanStr);
    if (isNaN(num) || num === 0) return '—';

    const adjustedNum = num + (seamAllowance > 0 ? seamAllowance : 0);

    if (unit === 'cm') {
      const cmVal = Math.round(adjustedNum * 2.54 * 10) / 10;
      return `${cmVal} cm`;
    }

    if (seamAllowance === 0) {
      return valStr.endsWith('"') ? valStr : `${valStr}"`;
    }

    return `${adjustedNum.toFixed(1)}"`;
  };

  const handlePhotoUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      const newUrl = URL.createObjectURL(file);
      setClientPhoto(newUrl);
      if (onUpdateClientPhoto) {
        onUpdateClientPhoto(client.id, newUrl);
      }
    }
  };

  const customObj = m.customMeasurements || {};
  const customItems = Object.entries(customObj).map(([name, raw]) => ({
    label: name,
    raw: String(raw),
    key: `custom_${name}`
  }));

  const handleCopySpec = () => {
    let customText = '';
    if (customItems.length > 0) {
      customText = '\nCUSTOM & ATELIER MEASUREMENTS:\n' +
        customItems.map((item) => `- ${item.label}: ${formatVal(item.raw)}`).join('\n') + '\n';
    }

    const text = `
MASTER TAILOR MEASUREMENT SPEC SHEET
------------------------------------
Client: ${client.name} (${client.garmentTag})
Phone: ${client.phone}
Assigned Designer: ${client.assignedDesigner || 'Master Atelier'}

UPPER BODY MEASUREMENTS:
- Bust/Chest: ${formatVal(m.bustOrChest || m.bust || m.chest)}
- Waist: ${formatVal(m.waist)}
- Shoulder Width: ${formatVal(m.shoulderWidth || m.shoulder)}
- Sleeve Length: ${formatVal(m.sleeveLength)}
- Full Garment Length: ${formatVal(m.fullLength)}
- Underbust: ${formatVal(m.underbust)}
- Round Sleeve/Armhole: ${formatVal(m.roundSleeves)}

LOWER BODY MEASUREMENTS:
- Hips: ${formatVal(m.hips)}
- Thigh: ${formatVal(m.thigh)}
- Knee: ${formatVal(m.knee)}
- Inseam: ${formatVal(m.inseam)}
- Ankle/Cuff: ${formatVal(m.ankle)}
${customText}
Seam Allowance Applied: +${seamAllowance}"
Unit: ${unit.toUpperCase()}
------------------------------------
Generated by Master Atelier Cutting Sheet
    `.trim();

    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleSpeakMeasurements = () => {
    if (!('speechSynthesis' in window)) return;

    if (isSpeaking) {
      window.speechSynthesis.cancel();
      setIsSpeaking(false);
      return;
    }

    const bustStr = formatVal(m.bustOrChest || m.bust || m.chest);
    const waistStr = formatVal(m.waist);
    const hipsStr = formatVal(m.hips);
    const shoulderStr = formatVal(m.shoulderWidth || m.shoulder);
    const sleeveStr = formatVal(m.sleeveLength);
    const fullLenStr = formatVal(m.fullLength);

    const customSpoken = customItems.map((item) => {
      const v = formatVal(item.raw);
      return v !== '—' ? `${item.label}: ${v}.` : null;
    });

    const parts = [
      `Full measurement profile for ${client.name}.`,
      bustStr !== '—' ? `Bust or chest: ${bustStr}.` : null,
      waistStr !== '—' ? `Waist: ${waistStr}.` : null,
      hipsStr !== '—' ? `Hips: ${hipsStr}.` : null,
      shoulderStr !== '—' ? `Shoulder: ${shoulderStr}.` : null,
      sleeveStr !== '—' ? `Sleeve length: ${sleeveStr}.` : null,
      fullLenStr !== '—' ? `Full length: ${fullLenStr}.` : null,
      ...customSpoken,
      'Ready for fabric cutting.'
    ].filter(Boolean);

    const textToRead = parts.join(' ');

    const utterance = new SpeechSynthesisUtterance(textToRead);
    utterance.rate = 0.95;
    utterance.onend = () => setIsSpeaking(false);
    utterance.onerror = () => setIsSpeaking(false);

    setIsSpeaking(true);
    window.speechSynthesis.speak(utterance);
  };

  const toggleCheck = (key: string) => {
    setChecklist((prev) => ({ ...prev, [key]: !prev[key] }));
  };

  const isMaleCategory = m.genderCategory === 'Male' || (!m.genderCategory && Boolean(m.chest && !m.bust));

  // Structured measurement sections for masters
  const upperBodyItems = isMaleCategory
    ? [
        { label: 'Chest Circumference', raw: m.chest || m.bustOrChest || m.bust, key: 'chest' },
        { label: 'Waist (Natural)', raw: m.waist, key: 'waist' },
        { label: 'Shoulder Width', raw: m.shoulderWidth || m.shoulder, key: 'shoulder' },
        { label: 'Sleeve Length', raw: m.sleeveLength, key: 'sleeveLength' },
        { label: 'Full Garment Length', raw: m.fullLength, key: 'fullLength' },
        { label: 'Top / Shirt Length', raw: m.topLength, key: 'topLength' },
        { label: 'Neck Circumference', raw: m.neck, key: 'neck' },
        { label: 'Round Sleeve / Bicep', raw: m.roundSleeves, key: 'roundSleeves' },
        { label: 'Neck-to-Waist', raw: m.neckToWaist, key: 'neckToWaist' }
      ]
    : [
        { label: 'Bust Circumference', raw: m.bust || m.bustOrChest || m.chest, key: 'bust' },
        { label: 'Waist (Natural)', raw: m.waist, key: 'waist' },
        { label: 'Shoulder Width', raw: m.shoulderWidth || m.shoulder, key: 'shoulder' },
        { label: 'Sleeve Length', raw: m.sleeveLength, key: 'sleeveLength' },
        { label: 'Full Garment Length', raw: m.fullLength, key: 'fullLength' },
        { label: 'Underbust', raw: m.underbust, key: 'underbust' },
        { label: 'Breast Length / Apex', raw: m.breastLength, key: 'breastLength' },
        { label: 'Top / Blouse Length', raw: m.topLength, key: 'topLength' },
        { label: 'Neck-to-Waist', raw: m.neckToWaist, key: 'neckToWaist' },
        { label: 'Round Sleeve / Bicep', raw: m.roundSleeves, key: 'roundSleeves' },
        { label: 'Neck Circumference', raw: m.neck, key: 'neck' }
      ];

  const lowerBodyItems = isMaleCategory
    ? [
        { label: 'Seat / Hips', raw: m.hips, key: 'hips' },
        { label: 'Thigh Circumference', raw: m.thigh, key: 'thigh' },
        { label: 'Knee Circumference', raw: m.knee, key: 'knee' },
        { label: 'Inseam / Crotch to Hem', raw: m.inseam, key: 'inseam' },
        { label: 'Ankle / Trouser Cuff', raw: m.ankle, key: 'ankle' },
        { label: 'Trouser / Bottoms Length', raw: m.skirtLength || m.fullLength, key: 'skirtLength' }
      ]
    : [
        { label: 'Full Hips', raw: m.hips, key: 'hips' },
        { label: 'Thigh Circumference', raw: m.thigh, key: 'thigh' },
        { label: 'Knee Circumference', raw: m.knee, key: 'knee' },
        { label: 'Inseam / Crotch to Hem', raw: m.inseam, key: 'inseam' },
        { label: 'Ankle / Cuff Width', raw: m.ankle, key: 'ankle' },
        { label: 'Skirt / Trouser Length', raw: m.skirtLength, key: 'skirtLength' }
      ];

  return (
    <div className="fixed inset-0 z-[110] bg-black/60 backdrop-blur-sm flex items-start sm:items-center justify-center p-2.5 sm:p-6 pt-[max(2.5rem,env(safe-area-inset-top))] sm:pt-6 overflow-y-auto font-['Outfit'] animate-fade-in">
      <div className="bg-[#F8FAF9] dark:bg-[#061E1B] text-slate-900 dark:text-slate-100 border border-slate-200/90 dark:border-white/10 w-full max-w-4xl rounded-2xl sm:rounded-3xl shadow-2xl overflow-hidden my-0 sm:my-auto flex flex-col max-h-[86vh] sm:max-h-[92vh] mt-1 sm:mt-0">
        
        {/* Sticky Header Bar */}
        <div className="bg-[#0D3B36] dark:bg-[#092825] p-3.5 sm:p-5 border-b border-[#082824] dark:border-white/10 flex items-center justify-between shrink-0">
          <div className="flex items-center gap-2.5 sm:gap-3">
            <div className="w-8 h-8 sm:w-10 sm:h-10 rounded-xl sm:rounded-2xl bg-white/10 text-[#DCA134] border border-[#DCA134]/40 flex items-center justify-center shadow-inner shrink-0">
              <Ruler className="w-4 h-4 sm:w-5 sm:h-5 text-[#DCA134]" />
            </div>
            <div>
              <div className="flex items-center gap-1.5 sm:gap-2 flex-wrap">
                <span className="font-extrabold text-[9px] sm:text-[10px] uppercase tracking-wider text-[#DCA134] bg-amber-400/15 px-2 py-0.5 rounded-full border border-amber-400/30">
                  MASTER CUTTING SPECIFICATION
                </span>
                <span className="text-[10px] sm:text-[11px] text-emerald-100 font-bold bg-emerald-900/60 px-2 py-0.5 rounded-full border border-emerald-700/50">
                  {isMaleCategory ? '♂ Male Spec Sheet' : '♀ Female Spec Sheet'}
                </span>
              </div>
              <h2 className="font-black text-base sm:text-2xl text-white dark:text-amber-300 tracking-tight mt-0.5 leading-tight">
                {client.name}'s Atelier Spec Sheet
              </h2>
            </div>
          </div>

          <button
            type="button"
            onClick={onClose}
            className="p-1.5 sm:p-2 rounded-full hover:bg-white/10 text-emerald-100 hover:text-white transition-colors cursor-pointer shrink-0 ml-2"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Modal Scrollable Body */}
        <div className="p-3 sm:p-6 space-y-4 sm:space-y-6 overflow-y-auto bg-[#F8FAF9] dark:bg-[#061E1B]">
          
          {/* Top Profile Card with Picture */}
          <div className="bg-white dark:bg-[#092825] border border-emerald-900/10 dark:border-white/10 rounded-2xl sm:rounded-3xl p-3.5 sm:p-5 shadow-xs flex flex-col sm:flex-row items-center sm:items-start justify-between gap-3 sm:gap-5 relative overflow-hidden">
            
            <div className="flex flex-col xs:flex-row items-center sm:items-center gap-3 sm:gap-4 text-center xs:text-left z-10 w-full sm:w-auto">
              
              {/* Picture on Top of Measurement Sheet */}
              <div className="relative group shrink-0">
                <div className="w-20 h-20 sm:w-28 sm:h-28 rounded-2xl sm:rounded-3xl overflow-hidden border-2 border-[#DCA134] shadow-md bg-[#0D3B36] relative flex items-center justify-center">
                  {clientPhoto ? (
                    <img
                      src={clientPhoto}
                      alt={client.name}
                      className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-300"
                    />
                  ) : (
                    <span className="font-black text-2xl sm:text-3xl text-[#DCA134]">
                      {client.initials || client.name.substring(0, 2).toUpperCase()}
                    </span>
                  )}
                  <div className="absolute inset-0 bg-black/30 opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center">
                    <label className="p-1.5 sm:p-2 rounded-full bg-amber-500 text-slate-950 cursor-pointer shadow-md hover:scale-110 transition-transform">
                      <Camera className="w-3.5 h-3.5 sm:w-4 sm:h-4 text-[#0D3B36]" />
                      <input
                        type="file"
                        accept="image/*"
                        onChange={handlePhotoUpload}
                        className="hidden"
                      />
                    </label>
                  </div>
                </div>
                
                <span className="absolute -bottom-2 -right-1 bg-[#0D3B36] border border-amber-400 text-amber-300 text-[9px] sm:text-[10px] font-black px-2 py-0.5 rounded-full shadow-xs">
                  {client.initials || 'VIP'}
                </span>
              </div>

              <div className="space-y-1">
                <div className="flex flex-wrap items-center justify-center xs:justify-start gap-1.5 sm:gap-2">
                  <h3 className="text-lg sm:text-xl font-black text-slate-900 dark:text-slate-100">{client.name}</h3>
                  <span className="text-[10px] sm:text-xs font-black bg-amber-100 dark:bg-amber-950/80 text-amber-900 dark:text-amber-300 border border-amber-300 dark:border-amber-700 px-2 py-0.5 rounded-full">
                    {client.garmentTag || 'Couture Garment'}
                  </span>
                </div>

                <p className="text-[11px] sm:text-xs text-slate-600 dark:text-slate-300 font-medium flex items-center justify-center xs:justify-start gap-1.5 sm:gap-2 flex-wrap">
                  <span>Phone: <strong className="text-slate-900 dark:text-amber-300">{client.phone}</strong></span>
                  <span>•</span>
                  <span>Stage: <strong className="text-emerald-700 dark:text-emerald-400">{client.runwayStage}</strong></span>
                </p>

                <p className="text-[11px] sm:text-xs text-slate-500 dark:text-slate-400">
                  Assigned Cutter / Tailor: <span className="text-[#0D3B36] dark:text-amber-300 font-bold">{client.assignedDesigner || 'Master Atelier'}</span>
                </p>
              </div>

            </div>

            {/* Quick Master Controls (Units, Audio, Copy) */}
            <div className="flex flex-wrap items-center justify-center sm:justify-end gap-1.5 sm:gap-2 z-10 w-full sm:w-auto pt-1 sm:pt-0">
              
              {/* Inches vs CM Unit Switcher */}
              <div className="flex items-center p-0.5 sm:p-1 bg-slate-100 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-xl">
                <button
                  type="button"
                  onClick={() => setUnit('inches')}
                  className={`px-2.5 py-1 text-[11px] sm:text-xs font-black rounded-lg transition-all cursor-pointer ${
                    unit === 'inches'
                      ? 'bg-[#0D3B36] dark:bg-amber-400 text-white dark:text-[#0D3B36] shadow-xs'
                      : 'text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-slate-100'
                  }`}
                >
                  Inches (")
                </button>
                <button
                  type="button"
                  onClick={() => setUnit('cm')}
                  className={`px-2.5 py-1 text-[11px] sm:text-xs font-black rounded-lg transition-all cursor-pointer ${
                    unit === 'cm'
                      ? 'bg-[#0D3B36] dark:bg-amber-400 text-white dark:text-[#0D3B36] shadow-xs'
                      : 'text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-slate-100'
                  }`}
                >
                  CM
                </button>
              </div>

              {/* Seam Allowance Toggle */}
              <select
                value={seamAllowance}
                onChange={(e) => setSeamAllowance(parseFloat(e.target.value))}
                className="p-1.5 sm:p-2 rounded-xl bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-[11px] sm:text-xs font-extrabold text-[#0D3B36] dark:text-amber-300 focus:outline-none cursor-pointer shadow-2xs"
              >
                <option value={0}>Exact Raw Measure</option>
                <option value={0.5}>+0.5" Seam</option>
                <option value={0.75}>+0.75" Standard Seam</option>
                <option value={1.0}>+1.0" Couture Seam</option>
              </select>

              {/* Hands-Free Voice Dictation Button */}
              <button
                type="button"
                onClick={handleSpeakMeasurements}
                className={`p-1.5 sm:p-2 px-2.5 sm:px-3 rounded-xl border text-[11px] sm:text-xs font-bold flex items-center gap-1 sm:gap-1.5 transition-all cursor-pointer ${
                  isSpeaking
                    ? 'bg-rose-100 dark:bg-rose-950/80 border-rose-300 dark:border-rose-700 text-rose-800 dark:text-rose-300 animate-pulse'
                    : 'bg-white dark:bg-slate-800 border-slate-200 dark:border-slate-700 text-slate-700 dark:text-slate-200 hover:bg-slate-50 dark:hover:bg-slate-700 shadow-2xs'
                }`}
                title="Listen to hands-free voice readout while cutting fabric"
              >
                {isSpeaking ? <VolumeX className="w-3.5 h-3.5 text-rose-600 dark:text-rose-400" /> : <Volume2 className="w-3.5 h-3.5 text-[#DCA134]" />}
                <span>{isSpeaking ? 'Stop' : 'Read Aloud'}</span>
              </button>

              {/* Copy Spec Button */}
              <button
                type="button"
                onClick={handleCopySpec}
                className="p-1.5 sm:p-2 px-2.5 sm:px-3 rounded-xl bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 hover:bg-slate-50 dark:hover:bg-slate-700 text-slate-700 dark:text-slate-200 font-bold text-[11px] sm:text-xs flex items-center gap-1 sm:gap-1.5 transition-all shadow-2xs cursor-pointer"
                title="Copy full measurement spec to clipboard"
              >
                {copied ? <Check className="w-3.5 h-3.5 text-emerald-600 dark:text-emerald-400" /> : <Copy className="w-3.5 h-3.5 text-[#0D3B36] dark:text-amber-300" />}
                <span>{copied ? 'Copied' : 'Copy'}</span>
              </button>

              {/* Edit / Record Measurements Button */}
              {onOpenMeasurements && (
                <button
                  type="button"
                  onClick={() => onOpenMeasurements(client)}
                  className="p-1.5 sm:p-2 px-2.5 sm:px-3.5 rounded-xl bg-[#0D3B36] dark:bg-amber-400 hover:bg-[#082824] dark:hover:bg-amber-300 text-white dark:text-[#0D3B36] font-extrabold text-[11px] sm:text-xs flex items-center gap-1 sm:gap-1.5 transition-all shadow-xs cursor-pointer"
                  title="Take or edit measurements for this client"
                >
                  <Ruler className="w-3.5 h-3.5 text-[#DCA134] dark:text-[#0D3B36]" />
                  <span>Edit Tape</span>
                </button>
              )}

            </div>

          </div>

          {/* Detailed Measurement Grids */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4 sm:gap-6">
            
            {/* Column 1: Upper Body / Torso Specs */}
            <div className="bg-white dark:bg-[#092825] border border-slate-200/90 dark:border-white/10 rounded-2xl sm:rounded-3xl p-3.5 sm:p-5 space-y-3 sm:space-y-4 shadow-xs">
              <div className="flex items-center justify-between border-b border-slate-100 dark:border-slate-800 pb-2.5 sm:pb-3">
                <div className="flex items-center gap-2">
                  <div className="p-1.5 sm:p-2 rounded-xl bg-emerald-50 dark:bg-slate-800 border border-emerald-200 dark:border-slate-700 text-emerald-800">
                    <Shirt className="w-3.5 h-3.5 sm:w-4 sm:h-4 text-[#0D3B36] dark:text-amber-300" />
                  </div>
                  <div>
                    <h4 className="font-black text-xs sm:text-sm text-[#0D3B36] dark:text-[#DCA134]">UPPER BODY & TORSO</h4>
                    <p className="text-[9px] sm:text-[10px] text-slate-500 dark:text-slate-400 font-medium">Chest, sleeves, shoulder & bodice</p>
                  </div>
                </div>
                <span className="text-[9px] sm:text-[10px] font-black bg-emerald-100 dark:bg-emerald-950/80 text-emerald-900 dark:text-emerald-300 border border-emerald-200 dark:border-emerald-700 px-2 sm:px-2.5 py-0.5 rounded-full">
                  {upperBodyItems.length} Metrics
                </span>
              </div>

              <div className="grid grid-cols-2 gap-2 sm:gap-2.5">
                {upperBodyItems.map((item) => (
                  <div
                    key={item.key}
                    className="p-2.5 sm:p-3.5 rounded-xl sm:rounded-2xl bg-[#F3F7F5] dark:bg-slate-800/80 border border-emerald-900/10 dark:border-slate-700 flex flex-col justify-between hover:border-emerald-600/30 transition-colors"
                  >
                    <span className="text-[9px] sm:text-[10px] font-extrabold uppercase text-slate-500 dark:text-slate-400 tracking-wider truncate">
                      {item.label}
                    </span>
                    <span className="text-base sm:text-xl font-black text-[#0D3B36] dark:text-amber-300 tracking-tight mt-0.5 sm:mt-1">
                      {formatVal(item.raw)}
                    </span>
                  </div>
                ))}
              </div>
            </div>

            {/* Column 2: Lower Body & Trouser/Skirt Specs */}
            <div className="bg-white dark:bg-[#092825] border border-slate-200/90 dark:border-white/10 rounded-2xl sm:rounded-3xl p-3.5 sm:p-5 space-y-3 sm:space-y-4 shadow-xs">
              <div className="flex items-center justify-between border-b border-slate-100 dark:border-slate-800 pb-2.5 sm:pb-3">
                <div className="flex items-center gap-2">
                  <div className="p-1.5 sm:p-2 rounded-xl bg-amber-50 dark:bg-slate-800 border border-amber-200 dark:border-slate-700 text-amber-900">
                    <Scissors className="w-3.5 h-3.5 sm:w-4 sm:h-4 text-[#DCA134]" />
                  </div>
                  <div>
                    <h4 className="font-black text-xs sm:text-sm text-[#0D3B36] dark:text-[#DCA134]">LOWER BODY & BOTTOMS</h4>
                    <p className="text-[9px] sm:text-[10px] text-slate-500 dark:text-slate-400 font-medium">Hips, inseam, thigh & lengths</p>
                  </div>
                </div>
                <span className="text-[9px] sm:text-[10px] font-black bg-amber-100 dark:bg-amber-950/80 text-amber-900 dark:text-amber-300 border border-amber-200 dark:border-amber-700 px-2 sm:px-2.5 py-0.5 rounded-full">
                  {lowerBodyItems.length} Metrics
                </span>
              </div>

              <div className="grid grid-cols-2 gap-2 sm:gap-2.5">
                {lowerBodyItems.map((item) => (
                  <div
                    key={item.key}
                    className="p-2.5 sm:p-3.5 rounded-xl sm:rounded-2xl bg-[#F3F7F5] dark:bg-slate-800/80 border border-emerald-900/10 dark:border-slate-700 flex flex-col justify-between hover:border-amber-500/30 transition-colors"
                  >
                    <span className="text-[9px] sm:text-[10px] font-extrabold uppercase text-slate-500 dark:text-slate-400 tracking-wider truncate">
                      {item.label}
                    </span>
                    <span className="text-base sm:text-xl font-black text-[#0D3B36] dark:text-amber-300 tracking-tight mt-0.5 sm:mt-1">
                      {formatVal(item.raw)}
                    </span>
                  </div>
                ))}
              </div>
            </div>

          </div>

          {/* Custom & Additional Atelier Measurements Card */}
          {customItems.length > 0 && (
            <div className="bg-white dark:bg-[#092825] border border-amber-500/30 dark:border-amber-400/30 rounded-2xl sm:rounded-3xl p-3.5 sm:p-5 space-y-3 sm:space-y-4 shadow-xs">
              <div className="flex items-center justify-between border-b border-slate-100 dark:border-slate-800 pb-2.5 sm:pb-3">
                <div className="flex items-center gap-2">
                  <div className="p-1.5 sm:p-2 rounded-xl bg-amber-50 dark:bg-slate-800 border border-amber-200 dark:border-slate-700 text-amber-900">
                    <Sparkles className="w-3.5 h-3.5 sm:w-4 sm:h-4 text-[#DCA134]" />
                  </div>
                  <div>
                    <h4 className="font-black text-xs sm:text-sm text-[#0D3B36] dark:text-[#DCA134]">CUSTOM & ADDITIONAL MEASUREMENTS</h4>
                    <p className="text-[9px] sm:text-[10px] text-slate-500 dark:text-slate-400 font-medium">Bespoke atelier dynamic metrics</p>
                  </div>
                </div>
                <span className="text-[9px] sm:text-[10px] font-black bg-amber-100 dark:bg-amber-950/80 text-amber-900 dark:text-amber-300 border border-amber-200 dark:border-amber-700 px-2 sm:px-2.5 py-0.5 rounded-full">
                  {customItems.length} Metrics
                </span>
              </div>

              <div className="grid grid-cols-2 sm:grid-cols-3 gap-2 sm:gap-2.5">
                {customItems.map((item) => (
                  <div
                    key={item.key}
                    className="p-2.5 sm:p-3.5 rounded-xl sm:rounded-2xl bg-[#F3F7F5] dark:bg-slate-800/80 border border-amber-500/20 dark:border-slate-700 flex flex-col justify-between hover:border-amber-500/40 transition-colors"
                  >
                    <span className="text-[9px] sm:text-[10px] font-extrabold uppercase text-slate-500 dark:text-slate-400 tracking-wider truncate">
                      {item.label}
                    </span>
                    <span className="text-base sm:text-xl font-black text-[#0D3B36] dark:text-amber-300 tracking-tight mt-0.5 sm:mt-1">
                      {formatVal(item.raw)}
                    </span>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Master Tailor Workshop Cutting Checklist & Notes */}
          <div className="bg-white dark:bg-[#092825] border border-slate-200/90 dark:border-white/10 rounded-2xl sm:rounded-3xl p-3.5 sm:p-5 space-y-3 sm:space-y-4 shadow-xs">
            <div className="flex items-center justify-between border-b border-slate-100 dark:border-slate-800 pb-2.5 sm:pb-3">
              <h4 className="font-black text-xs sm:text-sm text-slate-900 dark:text-slate-100 flex items-center gap-2">
                <CheckCircle2 className="w-4 h-4 text-emerald-600 dark:text-emerald-400 shrink-0" />
                <span>Master Cutter Fabric Preparation Checklist</span>
              </h4>
              <span className="text-[10px] sm:text-xs text-slate-400 dark:text-slate-500 font-mono">Workshop Control</span>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-2 sm:gap-2.5 text-xs font-semibold">
              <label
                onClick={() => toggleCheck('fabricInspected')}
                className={`p-2.5 sm:p-3 rounded-xl sm:rounded-2xl border flex items-center gap-2.5 cursor-pointer transition-all ${
                  checklist.fabricInspected
                    ? 'bg-emerald-50 dark:bg-emerald-950/70 border-emerald-300 dark:border-emerald-700 text-emerald-950 dark:text-emerald-300 font-bold'
                    : 'bg-slate-50 dark:bg-slate-800 border-slate-200 dark:border-slate-700 text-slate-500 dark:text-slate-400'
                }`}
              >
                <div className={`w-4 h-4 rounded-md flex items-center justify-center border shrink-0 ${
                  checklist.fabricInspected ? 'bg-emerald-600 border-emerald-600 text-white' : 'border-slate-300 dark:border-slate-600'
                }`}>
                  {checklist.fabricInspected && <Check className="w-3 h-3 stroke-[3]" />}
                </div>
                <span>Fabric inspected & preshrunk</span>
              </label>

              <label
                onClick={() => toggleCheck('grainlineAligned')}
                className={`p-2.5 sm:p-3 rounded-xl sm:rounded-2xl border flex items-center gap-2.5 cursor-pointer transition-all ${
                  checklist.grainlineAligned
                    ? 'bg-emerald-50 dark:bg-emerald-950/70 border-emerald-300 dark:border-emerald-700 text-emerald-950 dark:text-emerald-300 font-bold'
                    : 'bg-slate-50 dark:bg-slate-800 border-slate-200 dark:border-slate-700 text-slate-500 dark:text-slate-400'
                }`}
              >
                <div className={`w-4 h-4 rounded-md flex items-center justify-center border shrink-0 ${
                  checklist.grainlineAligned ? 'bg-emerald-600 border-emerald-600 text-white' : 'border-slate-300 dark:border-slate-600'
                }`}>
                  {checklist.grainlineAligned && <Check className="w-3 h-3 stroke-[3]" />}
                </div>
                <span>Grainline & motif matched</span>
              </label>

              <label
                onClick={() => toggleCheck('seamAdded')}
                className={`p-2.5 sm:p-3 rounded-xl sm:rounded-2xl border flex items-center gap-2.5 cursor-pointer transition-all ${
                  checklist.seamAdded
                    ? 'bg-emerald-50 dark:bg-emerald-950/70 border-emerald-300 dark:border-emerald-700 text-emerald-950 dark:text-emerald-300 font-bold'
                    : 'bg-slate-50 dark:bg-slate-800 border-slate-200 dark:border-slate-700 text-slate-500 dark:text-slate-400'
                }`}
              >
                <div className={`w-4 h-4 rounded-md flex items-center justify-center border shrink-0 ${
                  checklist.seamAdded ? 'bg-emerald-600 border-emerald-600 text-white' : 'border-slate-300 dark:border-slate-600'
                }`}>
                  {checklist.seamAdded && <Check className="w-3 h-3 stroke-[3]" />}
                </div>
                <span>+{seamAllowance}" Seam Allowance Added</span>
              </label>
            </div>
          </div>

        </div>

        {/* Modal Footer */}
        <div className="bg-white dark:bg-[#061E1B] p-3 sm:p-5 border-t border-slate-200 dark:border-white/10 flex items-center justify-between shrink-0 gap-2 no-print">
          <button
            type="button"
            onClick={onClose}
            className="px-3.5 sm:px-5 py-2 sm:py-2.5 rounded-xl sm:rounded-2xl bg-slate-100 dark:bg-slate-800 hover:bg-slate-200 dark:hover:bg-slate-700 text-slate-800 dark:text-slate-200 font-extrabold text-xs transition-all cursor-pointer"
          >
            Close Spec Sheet
          </button>

          <button
            type="button"
            onClick={() => window.print()}
            className="px-4 sm:px-6 py-2 sm:py-2.5 rounded-xl sm:rounded-2xl bg-[#0D3B36] dark:bg-amber-400 hover:bg-[#082824] dark:hover:bg-amber-300 text-white dark:text-[#0D3B36] font-extrabold text-xs shadow-md transition-all active:scale-95 flex items-center gap-1.5 sm:gap-2 cursor-pointer"
          >
            <Printer className="w-3.5 h-3.5 sm:w-4 sm:h-4 text-[#DCA134] dark:text-[#0D3B36]" />
            <span>Print Spec Sheet</span>
          </button>
        </div>

      </div>

      {/* Dedicated Printable Master Spec Sheet (Visible ONLY during window.print()) */}
      <div className="printable-spec-sheet hidden print:block bg-white text-slate-900 font-['Outfit']">
        
        {/* Header Block with App Logo & Letterhead */}
        <div className="border-b-2 border-[#0D3B36] pb-3 mb-3 flex items-center justify-between">
          <div className="flex items-center gap-3">
            {studioSettings?.logoUrl ? (
              <div className="w-12 h-12 rounded-xl bg-[#061E1B] border-2 border-[#DCA134] overflow-hidden shadow-md shrink-0 flex items-center justify-center">
                <img src={studioSettings.logoUrl} alt="App Logo" className="w-full h-full object-cover" />
              </div>
            ) : (
              <div className="w-12 h-12 rounded-xl bg-[#0D3B36] text-[#DCA134] border-2 border-[#DCA134] flex flex-col items-center justify-center shrink-0 p-1 shadow-md">
                <span className="font-['Cinzel',serif] font-black text-amber-300 text-lg leading-none">
                  {studioSettings?.studioName ? studioSettings.studioName.charAt(0).toUpperCase() : 'M'}
                </span>
                <span className="text-[5px] tracking-widest uppercase font-black text-amber-200 mt-0.5">
                  MOKARS
                </span>
              </div>
            )}
            <div>
              <span className="text-[9px] font-black uppercase tracking-widest bg-[#0D3B36] text-[#DCA134] px-2 py-0.5 rounded">
                MASTER ATELIER COUTURE SPECIFICATION
              </span>
              <h1 className="text-xl font-black text-[#0D3B36] uppercase tracking-tight mt-0.5">
                {studioSettings?.studioName || 'TAILOR PRO STUDIO'}
              </h1>
              <p className="text-[9px] font-bold text-slate-500 uppercase tracking-wider">
                Master Pattern Cutting & Workshop Fitting Blueprint
              </p>
            </div>
          </div>

          <div className="text-right space-y-0.5">
            <div className="inline-block bg-emerald-50 border border-emerald-300 px-2 py-0.5 rounded text-emerald-950 text-xs font-mono font-black">
              REF: SPEC-#{client.id.toUpperCase().slice(-8)}
            </div>
            <p className="text-[10px] font-bold text-slate-600">
              DATE: {new Date().toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' })}
            </p>
            <p className="text-[10px] font-mono text-slate-500">
              UNIT: {unit.toUpperCase()} | SEAM: +{seamAllowance}"
            </p>
          </div>
        </div>

        {/* Client Dossier Table Block */}
        <div className="bg-slate-50 border border-slate-300 rounded-xl p-3 mb-3 grid grid-cols-3 gap-2.5 text-xs">
          <div>
            <span className="text-[9px] font-extrabold uppercase text-slate-500 block">CLIENT NAME</span>
            <span className="font-black text-sm text-[#0D3B36]">{client.name}</span>
          </div>

          <div>
            <span className="text-[9px] font-extrabold uppercase text-slate-500 block">GARMENT / STYLE TAG</span>
            <span className="font-black text-sm text-slate-900">{client.garmentTag || 'Custom Garment'}</span>
          </div>

          <div>
            <span className="text-[9px] font-extrabold uppercase text-slate-500 block">TELEPHONE NUMBER</span>
            <span className="font-bold text-sm text-slate-900">{client.phone}</span>
          </div>

          <div>
            <span className="text-[9px] font-extrabold uppercase text-slate-500 block">ASSIGNED CUTTER / TAILOR</span>
            <span className="font-bold text-slate-900">{client.assignedDesigner || 'Master Atelier'}</span>
          </div>

          <div>
            <span className="text-[9px] font-extrabold uppercase text-slate-500 block">PRODUCTION STAGE</span>
            <span className="font-extrabold text-emerald-900 uppercase">{client.runwayStage}</span>
          </div>

          <div>
            <span className="text-[9px] font-extrabold uppercase text-slate-500 block">SPECIFICATION CATEGORY</span>
            <span className="font-extrabold text-[#0D3B36]">{isMaleCategory ? '♂ Male Fitting' : '♀ Female Fitting'}</span>
          </div>
        </div>

        {/* Structured 2-Column Measurement Spec Tables */}
        <div className="grid grid-cols-2 gap-3 mb-3">
          
          {/* Upper Body Table */}
          <div className="border border-slate-300 rounded-xl overflow-hidden">
            <div className="bg-[#0D3B36] text-white px-3 py-1.5 text-xs font-black uppercase tracking-wider flex items-center justify-between">
              <span>UPPER BODY & TORSO SPECIFICATIONS</span>
              <span className="text-[#DCA134] text-[10px]">{upperBodyItems.length} METRICS</span>
            </div>
            <table className="w-full text-xs text-left border-collapse">
              <thead>
                <tr className="bg-slate-100 border-b border-slate-200 text-[9px] font-black text-slate-500 uppercase">
                  <th className="p-1.5 border-r border-slate-200">METRIC</th>
                  <th className="p-1.5 border-r border-slate-200 text-center">VALUE ({unit.toUpperCase()})</th>
                  <th className="p-1.5 text-center">TARGET CUT</th>
                </tr>
              </thead>
              <tbody>
                {upperBodyItems.map((item, i) => (
                  <tr key={item.key} className={i % 2 === 0 ? 'bg-white' : 'bg-slate-50/50'}>
                    <td className="p-1.5 border-r border-b border-slate-200 font-bold text-slate-800">{item.label}</td>
                    <td className="p-1.5 border-r border-b border-slate-200 text-center font-black text-[#0D3B36]">{formatVal(item.raw)}</td>
                    <td className="p-1.5 border-b border-slate-200 text-center font-mono font-bold text-slate-700">
                      {formatVal(item.raw) !== '—' ? formatVal(item.raw) : '—'}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          {/* Lower Body Table */}
          <div className="border border-slate-300 rounded-xl overflow-hidden">
            <div className="bg-[#0D3B36] text-white px-3 py-1.5 text-xs font-black uppercase tracking-wider flex items-center justify-between">
              <span>LOWER BODY & BOTTOMS SPECIFICATIONS</span>
              <span className="text-[#DCA134] text-[10px]">{lowerBodyItems.length} METRICS</span>
            </div>
            <table className="w-full text-xs text-left border-collapse">
              <thead>
                <tr className="bg-slate-100 border-b border-slate-200 text-[9px] font-black text-slate-500 uppercase">
                  <th className="p-1.5 border-r border-slate-200">METRIC</th>
                  <th className="p-1.5 border-r border-slate-200 text-center">VALUE ({unit.toUpperCase()})</th>
                  <th className="p-1.5 text-center">TARGET CUT</th>
                </tr>
              </thead>
              <tbody>
                {lowerBodyItems.map((item, i) => (
                  <tr key={item.key} className={i % 2 === 0 ? 'bg-white' : 'bg-slate-50/50'}>
                    <td className="p-1.5 border-r border-b border-slate-200 font-bold text-slate-800">{item.label}</td>
                    <td className="p-1.5 border-r border-b border-slate-200 text-center font-black text-[#0D3B36]">{formatVal(item.raw)}</td>
                    <td className="p-1.5 border-b border-slate-200 text-center font-mono font-bold text-slate-700">
                      {formatVal(item.raw) !== '—' ? formatVal(item.raw) : '—'}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          {/* Printable Custom Measurements Section */}
          {customItems.length > 0 && (
            <div className="border border-slate-300 rounded-xl overflow-hidden mb-3">
              <div className="bg-[#0D3B36] text-white px-3 py-1 text-xs font-black uppercase tracking-wider flex items-center justify-between">
                <span>CUSTOM & ATELIER MEASUREMENTS</span>
                <span className="text-[#DCA134] text-[10px]">{customItems.length} METRICS</span>
              </div>
              <table className="w-full text-xs text-left border-collapse">
                <thead>
                  <tr className="bg-slate-100 border-b border-slate-200 text-[9px] font-black text-slate-500 uppercase">
                    <th className="p-1.5 border-r border-slate-200">METRIC</th>
                    <th className="p-1.5 border-r border-slate-200 text-center">VALUE ({unit.toUpperCase()})</th>
                    <th className="p-1.5 text-center">TARGET CUT</th>
                  </tr>
                </thead>
                <tbody>
                  {customItems.map((item, i) => (
                    <tr key={item.key} className={i % 2 === 0 ? 'bg-white' : 'bg-slate-50/50'}>
                      <td className="p-1.5 border-r border-b border-slate-200 font-bold text-slate-800">{item.label}</td>
                      <td className="p-1.5 border-r border-b border-slate-200 text-center font-black text-[#0D3B36]">{formatVal(item.raw)}</td>
                      <td className="p-1.5 border-b border-slate-200 text-center font-mono font-bold text-slate-700">
                        {formatVal(item.raw) !== '—' ? formatVal(item.raw) : '—'}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}

        </div>

        {/* Blueprint & Checklist Section */}
        <div className="grid grid-cols-3 gap-3 mb-3">
          
          {/* Mannequin Diagram */}
          <div className="border border-slate-300 rounded-xl p-2.5 flex flex-col items-center justify-center bg-slate-50/50 text-center">
            <span className="text-[9px] font-black uppercase text-slate-500 tracking-wider mb-1">BLUEPRINT CROQUIS</span>
            <div className="w-16 h-24 my-0.5">
              <svg viewBox="0 0 100 220" className="w-full h-full text-slate-600 stroke-current fill-none stroke-[1.5]">
                <circle cx="50" cy="20" r="10" />
                <path d="M47 30 L47 38 M53 30 L53 38" />
                <path d="M50 38 L30 46 L22 90 L20 120" />
                <path d="M50 38 L70 46 L78 90 L80 120" />
                <path d="M30 46 Q32 65 36 90 Q38 105 34 125 L32 170 L28 210" />
                <path d="M70 46 Q68 65 64 90 Q62 105 66 125 L68 170 L72 210" />
                <path d="M48 128 L47 170 L48 210" />
                <path d="M52 128 L53 170 L52 210" />
              </svg>
            </div>
            <span className="text-[9px] font-bold text-[#0D3B36] uppercase">{client.garmentTag || 'ATELIER PATTERN'}</span>
          </div>

          {/* Master Workshop Cutting Checklist */}
          <div className="col-span-2 border border-slate-300 rounded-xl p-2.5 bg-white space-y-1.5">
            <span className="text-[9px] font-black uppercase text-[#0D3B36] tracking-wider block border-b border-slate-200 pb-1">
              MASTER CUTTER FABRIC PREPARATION CHECKLIST
            </span>

            <div className="grid grid-cols-2 gap-1.5 text-xs font-bold text-slate-800 pt-0.5">
              <div className="flex items-center gap-1.5">
                <span className={`w-3.5 h-3.5 rounded border flex items-center justify-center text-[9px] font-black ${checklist.fabricInspected ? 'bg-[#0D3B36] text-white border-[#0D3B36]' : 'border-slate-300'}`}>
                  {checklist.fabricInspected ? '✓' : ''}
                </span>
                <span>Fabric Inspected & Preshrunk</span>
              </div>

              <div className="flex items-center gap-1.5">
                <span className={`w-3.5 h-3.5 rounded border flex items-center justify-center text-[9px] font-black ${checklist.grainlineAligned ? 'bg-[#0D3B36] text-white border-[#0D3B36]' : 'border-slate-300'}`}>
                  {checklist.grainlineAligned ? '✓' : ''}
                </span>
                <span>Grainline & Motif Matched</span>
              </div>

              <div className="flex items-center gap-1.5">
                <span className={`w-3.5 h-3.5 rounded border flex items-center justify-center text-[9px] font-black ${checklist.seamAdded ? 'bg-[#0D3B36] text-white border-[#0D3B36]' : 'border-slate-300'}`}>
                  {checklist.seamAdded ? '✓' : ''}
                </span>
                <span>+{seamAllowance}" Seam Allowance Verified</span>
              </div>

              <div className="flex items-center gap-1.5">
                <span className="w-3.5 h-3.5 rounded border border-slate-300 flex items-center justify-center text-[9px] font-black">✓</span>
                <span>Traditional Lining Precut</span>
              </div>
            </div>

            <div className="pt-1 text-[9px] text-slate-500 font-medium italic border-t border-slate-100">
              Notes: {client.notes || 'Ensure 2-inch side seam allowances reserved for future fitting adjustments.'}
            </div>
          </div>

        </div>

        {/* Master Cutter Sign-Off & Official Stamp Block */}
        <div className="border-t-2 border-[#0D3B36] pt-2 mt-2 flex items-end justify-between">
          <div className="space-y-0.5">
            <span className="text-[8px] font-black text-slate-500 uppercase tracking-widest block">WORKSHOP APPROVAL & QC</span>
            <p className="text-xs font-extrabold text-[#0D3B36]">Verified by Master Pattern Cutter</p>
            <p className="text-[9px] text-slate-400 font-mono">Tailor Pro Studio Atelier System • QC Passed</p>
          </div>

          <div className="flex items-center gap-5">
            <div className="text-center">
              <div className="w-28 border-b border-slate-900 h-5 mb-0.5"></div>
              <span className="text-[8px] font-bold text-slate-500 uppercase">MASTER TAILOR SIGNATURE</span>
            </div>

            <div className="text-center">
              <div className="w-20 border-b border-slate-900 h-5 mb-0.5"></div>
              <span className="text-[8px] font-bold text-slate-500 uppercase">DATE APPROVED</span>
            </div>

            <div className="w-14 h-14 rounded-full border-2 border-dashed border-[#0D3B36] flex flex-col items-center justify-center text-center p-0.5 shrink-0">
              <span className="text-[6px] font-black text-[#0D3B36] uppercase leading-none">OFFICIAL STAMP</span>
              <span className="text-[8px] font-black text-[#DCA134] mt-0.5">PASSED</span>
            </div>
          </div>
        </div>

      </div>

    </div>
  );
};
